### ISSUE TITLE
0.1.0 Baneslayer Masternode Configuration

### ISSUE THREAD

**Issue by detroitpro** [akroma-project/akroma-masternode-management#4]
### Intro
The next major release of akroma will contain a number of improvements and features. One area that we are working to adjust is the level of protection provided by those running node with RPC available on the public internet. 

### Masternode Configuration
During the past week many masternode operators were forced to apply complex firewall rules to protect their nodes from a massive effort to attack anyone running the geth RPC client on the public internet. 

With this release; those rules are no longer required. :+1:  There is one additional step of configuring an akroma masternode but overall the process should one of the most simple masternode configurations.

### Current Masternode Users
- Downloaded the latest "baneslayer" release https://github.com/akroma-project/akroma/releases
- Replace `/usr/sbin/geth` with the file you downloaded
- Edit `/etc/systemd/system/akromanode.service`
- Change the line that starts with `ExecStart`
- To be: `ExecStart=/usr/sbin/geth --masternode --rpcport 8545 --rpcuser UID --rpcpassword PAS`
- Be sure to set your port/uid/pass as you want.

#### Next, akroma.io
- Login to https://akroma.io
- Find your masternode
- Edit the `username` and `password` and enter the uid/pass that you setup on your masternode

### New Masternode Users
- Documentation and scripts for baneslayer fresh installs are being created now
- Follow the current scripts and then edit as described above.

**Comment by seanjnkns** [comment]
I think we can go ahead and close this "Issue" given the wiki and docs have been updated.
